package br.com.luccasoftware.api_dw.jpa;

import java.util.ArrayList;
import java.util.List;

public class DadosExtras {

    public  String buscarDados(List<Object[]> dados, int id, int posicao) {
        for (Object[] registro : dados) {
            if ((int) registro[0] == id) {
                return registro[posicao].toString();
            }
        }
        return ""; // Retorna null caso o ID não seja encontrado
    }

    public List<Object[]> dadosExtras() {

        List<Object[]> dados = new ArrayList<>();

        // Adicionando os dados completos
        dados.add(new Object[]{3, "Municipal", "Concurso Público", "Jurídica"});
        dados.add(new Object[]{4, "Privada", "Vestibular", "Educação"});
        dados.add(new Object[]{5, "Privada", "Vestibular", "Administração"});
        dados.add(new Object[]{7, null, null, null});
        dados.add(new Object[]{8, null, null, null});
        dados.add(new Object[]{9, "Federal", "Processo Seletivo", "Jurídica"});
        dados.add(new Object[]{10, "Municipal", "Concurso Público", "Administração"});
        dados.add(new Object[]{11, "Estadual", "Concurso Público", "Administração, TI, Jurídica e Saúde"});
        dados.add(new Object[]{12, "Federal", "Concurso Público", "Educação, TI, Administração, Assistência Social, Saúde"});
        dados.add(new Object[]{13, "Federal", "Concurso Público", "Educação, TI, Administração, Assistência Social, Saúde"});
        dados.add(new Object[]{14, "Estadual", "Concurso Público", "Assistência Social"});
        dados.add(new Object[]{15, "Federal", "Concurso Público", "Ciência e TI"});
        dados.add(new Object[]{16, "Federal", "Concurso Público", "Educação"});
        dados.add(new Object[]{17, null, null, null});
        dados.add(new Object[]{18, "Federal", "Processo Seletivo", "Jurídica"});
        dados.add(new Object[]{19, "Federal", "Processo Seletivo", "Saúde"});
        dados.add(new Object[]{20, "Federal", "Concurso Público", "Saúde"});
        dados.add(new Object[]{21, "Federal", "Concurso Público", "Saúde"});
        dados.add(new Object[]{22, "Federal", "Concurso Público", "Saúde"});
        dados.add(new Object[]{23, "Federal", "Concurso Público", "Saúde"});
        dados.add(new Object[]{24, "Federal", "Concurso Público", "Assistência Social"});
        dados.add(new Object[]{25, "Federal", "Concurso Público", "Administração"});
        dados.add(new Object[]{26, "Estadual", "Concurso Público", "Jurídica"});
        dados.add(new Object[]{27, "Federal", "Concurso Público", "Saúde"});
        dados.add(new Object[]{28, "Federal", "Concurso Público", "Assistência Social"});
        dados.add(new Object[]{29, "Federal", "Concurso Público", "Administração"});
        dados.add(new Object[]{30, "Federal", "Concurso Público", "Saúde"});
        dados.add(new Object[]{31, "Federal", "Concurso Público", "Assistência Social"});
        dados.add(new Object[]{32, "Federal", "Concurso Público", "Administração"});
        dados.add(new Object[]{33, "Estadual", "Concurso Público", "Rural"});
        dados.add(new Object[]{34, "Federal", "Concurso Público", "Saúde"});
        dados.add(new Object[]{35, "Federal", "Concurso Público", "Assistência Social"});
        dados.add(new Object[]{36, "Federal", "Concurso Público", "Administração"});
        dados.add(new Object[]{37, "Federal", "Concurso Público", "Saúde"});
        dados.add(new Object[]{38, "Federal", "Concurso Público", "Assistência Social"});
        dados.add(new Object[]{39, "Federal", "Concurso Público", "Administração"});
        dados.add(new Object[]{40, "Federal", "Concurso Público", "Saúde"});
        dados.add(new Object[]{41, "Federal", "Concurso Público", "Assistência Social"});
        dados.add(new Object[]{42, "Federal", "Processo Seletivo", "Administração"});
        dados.add(new Object[]{43, "Municipal", "Concurso Público", "Educação"});
        dados.add(new Object[]{44, "Federal", "Concurso Público", "Saúde"});
        dados.add(new Object[]{45, "Estadual", "Concurso Público", "Saúde"});
        dados.add(new Object[]{46, "Federal", "Concurso Público", "Saúde"});
        dados.add(new Object[]{47, "Federal", "Concurso Público", "Saúde"});
        dados.add(new Object[]{48, "Federal", "Concurso Público", "Saúde"});
        dados.add(new Object[]{49, "Federal", "Concurso Público", "Saúde"});
        dados.add(new Object[]{50, "Federal", "Concurso Público", "Saúde"});
        dados.add(new Object[]{51, "Federal", "Concurso Público", "Saúde"});
        dados.add(new Object[]{52, "Federal", "Concurso Público", "Saúde"});
        dados.add(new Object[]{53, "Federal", "Concurso Público", "Saúde"});
        dados.add(new Object[]{54, "Federal", "Concurso Público", "Saúde"});
        dados.add(new Object[]{55, "Federal", "Concurso Público", "Saúde"});
        dados.add(new Object[]{56, "Federal", "Concurso Público", "Saúde"});
        dados.add(new Object[]{57, "Federal", "Concurso Público", "Saúde"});
        dados.add(new Object[]{58, "Federal", "Concurso Público", "Saúde"});
        dados.add(new Object[]{59, "Federal", "Concurso Público", "Saúde"});
        dados.add(new Object[]{63, "Municipal", "Residência Médica", "Saúde"});
        dados.add(new Object[]{64, "Federal", "Concurso Público", "Saúde"});
        dados.add(new Object[]{65, "Federal", "Concurso Público", "Saúde"});
        dados.add(new Object[]{66, "Federal", "Concurso Público", "Saúde"});
        dados.add(new Object[]{67, "Federal", "Concurso Público", "Saúde"});
        dados.add(new Object[]{68, "Federal", "Concurso Público", "Saúde"});
        dados.add(new Object[]{69, "Federal", "Concurso Público", "Saúde"});
        dados.add(new Object[]{70, "Federal", "Concurso Público", "Saúde"});
        dados.add(new Object[]{71, "Federal", "Concurso Público", "Saúde"});
        dados.add(new Object[]{72, "Federal", "Concurso Público", "Saúde"});
        dados.add(new Object[]{76, "Estadual", "Processo Seletivo", "Administração"});
        dados.add(new Object[]{77, "Federal", "Concurso Público", "Saúde"});
        dados.add(new Object[]{78, "Federal", "Concurso Público", "Saúde"});
        dados.add(new Object[]{79, "Federal", "Concurso Público", "Saúde"});
        dados.add(new Object[]{80, "Federal", "Concurso Público", "Saúde"});
        dados.add(new Object[]{81, "Federal", "Concurso Público", "Saúde"});
        dados.add(new Object[]{82, "Federal", "Concurso Público", "Saúde"});
        dados.add(new Object[]{83, "Federal", "Concurso Público", "Saúde"});
        dados.add(new Object[]{85, "Municipal", "Concurso Público", "Administração e Educação"});
        dados.add(new Object[]{87, "Municipal", "Residência Médica", "Saúde"});
        dados.add(new Object[]{88, "Estadual", "Concurso Público", "Saneamento e Administrativo"});
        dados.add(new Object[]{89, "Federal", "Concurso Público", "Saúde"});
        dados.add(new Object[]{90, "Federal", "Concurso Público", "Saúde"});
        dados.add(new Object[]{91, "Federal", "Concurso Público", "Saúde"});
        dados.add(new Object[]{92, "Municipal", "Concurso Público", "Jurídica"});
        dados.add(new Object[]{93, "Estadual", "Processo Seletivo", "Administração, Segurança e Saúde"});
        dados.add(new Object[]{100, "Municipal", "Concurso Público", "Jurídica"});
        dados.add(new Object[]{101, "Municipal", "Concurso Público", "Administração e Educação"});
        dados.add(new Object[]{102, "Federal", "Concurso Público", "Saúde"});
        dados.add(new Object[]{103, "Federal", "Concurso Público", "Saúde"});
        dados.add(new Object[]{104, "Federal", "Concurso Público", "Administração"});
        dados.add(new Object[]{107, "Estadual", "Concurso Público", "Segurança"});
        dados.add(new Object[]{110, "Federal", "Concurso Público", "Administração"});
        dados.add(new Object[]{114, "Federal", "Concurso Público", "Administração"});
        dados.add(new Object[]{115, "Federal", "Concurso Público", "Saúde"});
        dados.add(new Object[]{116, "Federal", "Concurso Público", "Saúde"});
        dados.add(new Object[]{117, "Federal", "Concurso Público", "Administração"});
        dados.add(new Object[]{118, "Federal", "Concurso Público", "Saúde"});
        dados.add(new Object[]{119, "Federal", "Concurso Público", "Saúde"});
        dados.add(new Object[]{120, "Federal", "Concurso Público", "Administração"});
        dados.add(new Object[]{121, "Federal", "Concurso Público", "Saúde"});
        dados.add(new Object[]{122, "Federal", "Concurso Público", "Saúde"});
        dados.add(new Object[]{123, "Federal", "Concurso Público", "Administração"});
        dados.add(new Object[]{124, "Municipal", "Concurso Público", "Jurídica"});
        dados.add(new Object[]{149, "Municipal", "Concurso Público", "Administração"});
        dados.add(new Object[]{150, "Federal", "Concurso Público", "Saúde e Administrativo"});
        dados.add(new Object[]{151, "Estadual", "Concurso Público", "Administração"});
        dados.add(new Object[]{152, "Estadual", "Concurso Público", "Segurança"});
        dados.add(new Object[]{153, "Estadual", "Concurso Público", "Segurança"});
        dados.add(new Object[]{164, "Municipal", "Concurso Público", "Saúde e Administrativo"});
        dados.add(new Object[]{165, "Municipal", "Concurso Público", "Saúde"});
        dados.add(new Object[]{166, "Estadual", "Concurso Público", "Saúde"});
        dados.add(new Object[]{167, "Estadual", "Vestibular", "Administração"});
        dados.add(new Object[]{168, "Estadual", "Vestibular", "Saúde"});
        dados.add(new Object[]{171, "Estadual", "Concurso Público", "Segurança"});
        dados.add(new Object[]{173, "Estadual", "Concurso Público", "Segurança"});
        dados.add(new Object[]{174, "Municipal", "Processo Seletivo", "Saúde"});
        dados.add(new Object[]{178, "Estadual", "Concurso Público", "Saúde"});
        dados.add(new Object[]{179, "Estadual", "Concurso Público", "Saúde"});
        dados.add(new Object[]{180, "Estadual", "Concurso Público", "Administração"});
        dados.add(new Object[]{181, "Federal", "Concurso Público", "Administração"});
        dados.add(new Object[]{182, "Municipal", "Concurso Público", "Saúde"});
        dados.add(new Object[]{184, "Estadual", "Concurso Público", "Segurança"});
        dados.add(new Object[]{185, "Estadual", "Concurso Público", "Segurança"});
        dados.add(new Object[]{186, "Estadual", "Concurso Público", "Administração"});
        dados.add(new Object[]{187, "Estadual", "Concurso Público", "Segurança"});
        dados.add(new Object[]{188, "Estadual", "Concurso Público", "Segurança e Saúde"});
        dados.add(new Object[]{190, "Estadual", "Concurso Público", "Administração"});
        dados.add(new Object[]{191, "Estadual", null, null});
        dados.add(new Object[]{193, "Federal", "Concurso Público", "Administração e Educação"});
        dados.add(new Object[]{194, "Estadual", "Concurso Público", "Segurança"});
        dados.add(new Object[]{195, "Estadual", "Concurso Público", "Segurança"});
        dados.add(new Object[]{196, "Estadual", "Concurso Público", "Segurança"});
        dados.add(new Object[]{197, "Estadual", "Concurso Público", "Segurança"});
        dados.add(new Object[]{198, "Estadual", "Concurso Público", "Segurança"});
        dados.add(new Object[]{201, "Estadual", "Concurso Público", "Segurança"});
        dados.add(new Object[]{202, "Estadual", "Concurso Público", "Segurança"});
        dados.add(new Object[]{203, "Federal", "Concurso Público", "Administração, TI, Jurídica e Saúde"});
        dados.add(new Object[]{204, "Estadual", "Concurso Público", "Saúde e Administrativo"});
        dados.add(new Object[]{205, "Estadual", "Processo Seletivo", "Educação"});
        dados.add(new Object[]{206, "Estadual", "Processo Seletivo", "Educação"});
        dados.add(new Object[]{207, "Estadual", "Processo Seletivo", "Educação"});
        dados.add(new Object[]{208, "Estadual", "Concurso Público", "Administração"});
        dados.add(new Object[]{209, "Estadual", "Concurso Público", "Administração, Saúde e Rural"});
        dados.add(new Object[]{215, "Estadual", "Concurso Público", "Segurança"});
        dados.add(new Object[]{216, "Municipal", "Concurso Público", "Educação"});
        dados.add(new Object[]{217, "Estadual", "Concurso Público", "Segurança"});
        dados.add(new Object[]{218, "Federal", "Concurso Público", "Administração, TI, Jurídica e Saúde"});
        dados.add(new Object[]{219, null, null, null});
        dados.add(new Object[]{220, "Estadual", "Concurso Público", "Educação"});
        dados.add(new Object[]{221, "Federal", "Concurso Público", "Administração e Educação"});
        dados.add(new Object[]{222, "Federal", "Concurso Público", "Saúde e Administrativo"});
        dados.add(new Object[]{223, "Federal", "Processo Seletivo", "Administração"});
        dados.add(new Object[]{224, "Municipal", "Concurso Público", "Administração, TI, Jurídica e Saúde"});
        dados.add(new Object[]{225, "Municipal", "Concurso Público", "Educação, TI, Administração"});
        dados.add(new Object[]{226, "Privada", "Processo Seletivo", "Administração e Educação"});
        dados.add(new Object[]{244, "Municipal", "Concurso Público", "Saúde"});
        dados.add(new Object[]{246, "Municipal", "Concurso Público", "Saúde"});
        dados.add(new Object[]{247, "Municipal", "Processo Seletivo", "TI"});
        dados.add(new Object[]{248, "Municipal", "Processo Seletivo", "Administração e Educação"});
        dados.add(new Object[]{249, "Estadual", "Processo Seletivo", "Jurídica"});
        dados.add(new Object[]{250, "Municipal", "Concurso Público", "Administração"});
        dados.add(new Object[]{251, "Estadual", "Processo Seletivo", "Saúde"});
        dados.add(new Object[]{252, "Municipal", "Concurso Público", "Administração e Educação"});
        dados.add(new Object[]{253, "Municipal", "Concurso Público", "Administração"});
        dados.add(new Object[]{254, "Municipal", "Concurso Público", "Saúde"});
        dados.add(new Object[]{255, null, null, null});
        dados.add(new Object[]{256, "Municipal", "Concurso Público", "Educação, TI, Administração, Assistência Social, Saúde"});
        dados.add(new Object[]{257, null, null, null});
        dados.add(new Object[]{258, null, null, null});
        dados.add(new Object[]{259, "Municipal", "Concurso Público", "TI e Administração"});
        dados.add(new Object[]{260, "Federal", "Processo Seletivo", "Saúde"});
        dados.add(new Object[]{269, "Federal", "Processo Seletivo", "TI"});
        dados.add(new Object[]{270, "Federal", "Processo Seletivo", "Saúde"});
        dados.add(new Object[]{271, "Municipal", "Concurso Público", "Saúde"});
        dados.add(new Object[]{272, "Estadual", "Processo Seletivo", "Assistência Social"});
        dados.add(new Object[]{273, "Estadual", "Concurso Público", "Segurança"});
        dados.add(new Object[]{274, "Estadual", "Processo Seletivo", "Saúde"});
        dados.add(new Object[]{275, "Municipal", "Concurso Público", "Jurídica"});
        dados.add(new Object[]{276, "Estadual", "Processo Seletivo", "Saúde"});
        dados.add(new Object[]{277, "Federal", "Processo Seletivo", "Saúde"});
        dados.add(new Object[]{278, "Federal", "Processo Seletivo", "Saúde"});
        dados.add(new Object[]{279, "Federal", "Processo Seletivo", "Saúde"});
        dados.add(new Object[]{280, "Federal", "Processo Seletivo", "Saúde"});
        dados.add(new Object[]{281, "Federal", "Processo Seletivo", "Saúde"});
        dados.add(new Object[]{282, "Estadual", "Concurso Público", "Administração"});
        dados.add(new Object[]{283, "Municipal", "Concurso Público", "Educação"});
        dados.add(new Object[]{284, "Federal", "Processo Seletivo", "Saúde"});
        dados.add(new Object[]{285, "Federal", "Processo Seletivo", "Saúde"});
        dados.add(new Object[]{286, "Municipal", "Concurso Público", "Saúde"});
        dados.add(new Object[]{287, "Municipal", "Concurso Público", "Saúde"});
        dados.add(new Object[]{288, "Municipal", "Concurso Público", "Saúde"});
        dados.add(new Object[]{289, "Estadual", "Concurso Público", "Segurança"});
        dados.add(new Object[]{302, "Estadual", "Concurso Público", "Segurança"});
        dados.add(new Object[]{303, "Estadual", "Processo Seletivo", "Saúde"});
        dados.add(new Object[]{304, "Municipal", "Concurso Público", "Administração, Arquiteto e Engenheiro"});
        dados.add(new Object[]{305, "Municipal", "Concurso Público", "Saúde"});
        dados.add(new Object[]{306, null, null, null});
        dados.add(new Object[]{307, null, null, null});
        dados.add(new Object[]{308, null, null, null});
        dados.add(new Object[]{309, null, null, null});
        dados.add(new Object[]{310, null, null, null});
        dados.add(new Object[]{311, null, null, null});
        dados.add(new Object[]{312, "Federal", "Processo Seletivo", "Saúde"});
        dados.add(new Object[]{313, "Federal", "Processo Seletivo", "Saúde"});
        dados.add(new Object[]{314, "Federal", "Processo Seletivo", "Saúde"});
        dados.add(new Object[]{315, "Federal", "Concurso Público", "Engenharia Civil"});
        dados.add(new Object[]{316, null, null, null});
        dados.add(new Object[]{321, null, null, null});
        dados.add(new Object[]{322, "Federal", "Processo Seletivo", "Saúde"});
        dados.add(new Object[]{323, "Federal", "Processo Seletivo", "Saúde"});
        dados.add(new Object[]{324, "Federal", "Processo Seletivo", "Saúde"});
        dados.add(new Object[]{325, "Estadual", "Processo Seletivo", "Saúde"});
        dados.add(new Object[]{332, "Estadual", "Concurso Público", "Segurança"});
        dados.add(new Object[]{333, "Estadual", "Concurso Público", "Jurídica"});
        dados.add(new Object[]{334, "Estadual", "Concurso Público", "Jurídica"});
        dados.add(new Object[]{335, "Municipal", "Processo Seletivo", "Educação"});
        dados.add(new Object[]{336, "Estadual", "Processo Seletivo", "Saúde"});
        dados.add(new Object[]{339, "Municipal", "Processo Seletivo", "Educação"});
        dados.add(new Object[]{340, "Estadual", "Processo Seletivo", "Saúde, Assistente Social e Motorista"});
        dados.add(new Object[]{341, "Federal", "Processo Seletivo", "Contabilidade"});
        dados.add(new Object[]{342, "Estadual", "Processo Seletivo", "Saúde"});
        dados.add(new Object[]{348, null, null, null});
        dados.add(new Object[]{349, "Federal", "Residência Médica", "Saúde"});
        dados.add(new Object[]{350, "Federal", "Residência Médica", "Saúde"});
        dados.add(new Object[]{351, "Municipal", "Concurso Público", "Educação"});
        dados.add(new Object[]{354, "Federal", "Concurso Público", "Educação"});
        dados.add(new Object[]{355, "Federal", "Concurso Público", "Administração"});
        dados.add(new Object[]{356, "Estadual", "Residência Médica", "Saúde"});
        dados.add(new Object[]{357, null, null, null});
        dados.add(new Object[]{358, "Municipal", "Concurso Público", "Educação"});
        dados.add(new Object[]{359, "Estadual", "Concurso Público", "Administração"});
        dados.add(new Object[]{362, "Estadual", "Processo Seletivo", "Educação"});
        dados.add(new Object[]{363, "Estadual", "Vestibular", "Administração"});
        dados.add(new Object[]{364, "Estadual", "Concurso Público", "Administração"});
        dados.add(new Object[]{366, "Municipal", "Residência Médica", "Saúde"});
        dados.add(new Object[]{373, "Estadual", "Concurso Público", "Administração"});
        dados.add(new Object[]{374, "Privada", "Residência Médica", "Saúde"});
        dados.add(new Object[]{375, "Privada", "Residência Médica", "Saúde"});
        dados.add(new Object[]{376, "Municipal", "Concurso Público", "Saúde e Educação"});
        dados.add(new Object[]{377, "Estadual", "Concurso Público", "Segurança"});
        dados.add(new Object[]{378, "Federal", "Concurso Público", "Administração e Educação"});
        dados.add(new Object[]{380, "Federal", "Concurso Público", "Educação"});
        dados.add(new Object[]{381, "Estadual", "Concurso Público", "Educação"});
        dados.add(new Object[]{382, "Estadual", "Concurso Público", "Administração"});
        dados.add(new Object[]{383, "Estadual", "Concurso Público", "Segurança"});
        dados.add(new Object[]{384, "Estadual", "Concurso Público", "Segurança"});
        dados.add(new Object[]{385, "Estadual", "Concurso Público", "Segurança"});
        dados.add(new Object[]{386, "Estadual", "Concurso Público", "Segurança"});
        dados.add(new Object[]{387, "Estadual", "Concurso Público", "Segurança"});
        dados.add(new Object[]{388, "Municipal", "Concurso Público", "Administração"});
        dados.add(new Object[]{389, "Estadual", "Concurso Público", "Segurança"});
        dados.add(new Object[]{396, "Estadual", "Concurso Público", "Segurança"});
        dados.add(new Object[]{400, "Estadual", "Concurso Público", "Segurança"});
        dados.add(new Object[]{408, "Estadual", "Concurso Público", "TI"});
        dados.add(new Object[]{409, "Estadual", "Concurso Público", "Jurídico e Administração"});
        dados.add(new Object[]{410, "Estadual", "Concurso Público", "TI e Administração"});
        dados.add(new Object[]{411, null, null, null});
        dados.add(new Object[]{418, "Estadual", "Concurso Público", "Segurança"});
        dados.add(new Object[]{419, "Estadual", "Concurso Público", "Segurança"});
        dados.add(new Object[]{421, "Estadual", "Concurso Público", "Jurídico e Administração"});
        dados.add(new Object[]{422, "Estadual", "Concurso Público", "Segurança"});
        dados.add(new Object[]{424, "Estadual", "Concurso Público", "Segurança"});
        dados.add(new Object[]{425, "Estadual", "Concurso Público", "Segurança"});
        dados.add(new Object[]{429, "Estadual", "Concurso Público", "Segurança"});
        dados.add(new Object[]{430, "Estadual", "Concurso Público", "Segurança"});
        dados.add(new Object[]{431, "Estadual", "Processo Seletivo", "Saúde e Administrativo"});
        dados.add(new Object[]{432, "Federal", "Residência Médica", "Saúde"});
        dados.add(new Object[]{433, "Federal", "Residência Médica", "Saúde"});
        dados.add(new Object[]{434, "Municipal", "Concurso Público", "Saúde"});
        dados.add(new Object[]{435, "Municipal", "Concurso Público", "Saúde e Administrativo"});
        dados.add(new Object[]{436, "Estadual", "Concurso Público", "Saneamento e Administrativo"});
        dados.add(new Object[]{440, "Estadual", "Concurso Público", "TI e Administração"});
        dados.add(new Object[]{442, "Estadual", "Concurso Público", "Segurança"});
        dados.add(new Object[]{443, "Estadual", "Concurso Público", "Segurança"});
        dados.add(new Object[]{444, "Estadual", "Concurso Público", "Segurança"});
        dados.add(new Object[]{445, "Estadual", "Concurso Público", "Segurança"});
        dados.add(new Object[]{446, "Federal", "Concurso Público", "Administração e Educação"});
        dados.add(new Object[]{454, "Estadual", "Processo Seletivo", "Segurança"});
        dados.add(new Object[]{455, "Estadual", "Concurso Público", "Jurídica"});
        dados.add(new Object[]{470, "Municipal", "Concurso Público", "Administrativo, Previdenciário e TI"});
        dados.add(new Object[]{471, "Federal", "Concurso Público", "Educação"});
        dados.add(new Object[]{472, "Federal", "Concurso Público", "Administração"});
        dados.add(new Object[]{473, "Federal", "Concurso Público", "Administração, Segurança e Saúde"});
        dados.add(new Object[]{474, "Estadual", "Concurso Público", "Jurídica"});
        dados.add(new Object[]{475, "Estadual", "Residência Médica", "Saúde"});
        dados.add(new Object[]{476, "Estadual", "Concurso Público", "Educação"});
        dados.add(new Object[]{477, "Estadual", "Residência Médica", "Saúde"});
        dados.add(new Object[]{478, "Estadual", "Concurso Público", "Rural"});
        dados.add(new Object[]{511, "Estadual", "Concurso Público", "Meio Ambiente"});
        dados.add(new Object[]{544, "Estadual", "Concurso Público", "Segurança"});
        dados.add(new Object[]{545, "Estadual", "Processo Seletivo", "Segurança"});
        dados.add(new Object[]{546, "Estadual", "Processo Seletivo", "Segurança"});
        dados.add(new Object[]{547, null, null, null});
        dados.add(new Object[]{548, "Estadual", "Concurso Público", "Agropecuário"});
        dados.add(new Object[]{549, "Estadual", "Concurso Público", "Segurança"});
        dados.add(new Object[]{550, "Estadual", "Residência Médica", "Saúde"});
        dados.add(new Object[]{551, null, null, null});
        dados.add(new Object[]{552, null, null, null});
        dados.add(new Object[]{553, "Estadual", "Concurso Público", "Educação, TI, Administração, Assistência Social, Saúde"});
        dados.add(new Object[]{554, "Federal", "Concurso Público", "Administração e Educação"});
        dados.add(new Object[]{555, "Federal", "Concurso Público", "Educação"});
        dados.add(new Object[]{556, "Estadual", "Concurso Público", "Segurança e Educação"});
        dados.add(new Object[]{557, "Estadual", "Concurso Público", "Segurança"});
        dados.add(new Object[]{558, "Estadual", "Concurso Público", "Segurança e Saúde"});
        dados.add(new Object[]{559, null, null, null});
        dados.add(new Object[]{560, "Estadual", "Concurso Público", "Jurídica"});
        dados.add(new Object[]{561, "Federal", "Concurso Público", "Administração e Educação"});
        dados.add(new Object[]{562, "Municipal", "Concurso Público", "Educação"});
        dados.add(new Object[]{563, "Estadual", "Concurso Público", "Segurança"});
        dados.add(new Object[]{564, null, null, null});
        dados.add(new Object[]{565, null, null, null});
        dados.add(new Object[]{566, "Estadual", "Processo Seletivo", "Administração"});
        dados.add(new Object[]{567, "Federal", "Residência Médica", "Saúde"});
        dados.add(new Object[]{568, "Federal", "Residência Médica", "Saúde"});
        dados.add(new Object[]{569, "Municipal", "Concurso Público", "Educação"});
        dados.add(new Object[]{570, "Estadual", "Concurso Público", "Administração"});
        dados.add(new Object[]{571, null, null, null});
        dados.add(new Object[]{572, null, null, null});
        dados.add(new Object[]{573, null, null, null});
        dados.add(new Object[]{574, null, null, null});
        dados.add(new Object[]{575, "Estadual", "Concurso Público", "Educação"});
        dados.add(new Object[]{576, null, null, null});
        dados.add(new Object[]{577, null, null, null});
        dados.add(new Object[]{578, "Federal", "Concurso Público", "Administração, Educação, Técnico, Assistente Social, Saúde, Analista , Economista, Bibliotecário"});
        dados.add(new Object[]{579, "Federal", "Concurso Público", "Tecnologista"});
        dados.add(new Object[]{580, "Federal", "Concurso Público", "Pesquisador"});
        dados.add(new Object[]{581, "Estadual", "Concurso Público", "Segurança"});
        dados.add(new Object[]{582, "Estadual", "Concurso Público", "Segurança"});
        dados.add(new Object[]{583, "Estadual", "Concurso Público", "Segurança"});
        dados.add(new Object[]{584, "Estadual", "Concurso Público", "Segurança"});
        dados.add(new Object[]{585, "Estadual", "Processo Seletivo", "Saúde"});
        dados.add(new Object[]{586, "Federal", "Concurso Público", "Educação"});
        dados.add(new Object[]{587, "Federal", "Concurso Público", "Administração e Educação"});
        dados.add(new Object[]{588, "Estadual", "Concurso Público", "Segurança"});
        dados.add(new Object[]{589, "Estadual", "Concurso Público", "Segurança"});
        dados.add(new Object[]{590, "Municipal", "Concurso Público", "Saúde e Administrativo"});
        dados.add(new Object[]{591, "Municipal", "Processo Seletivo", "Administração"});
        dados.add(new Object[]{592, "Municipal", "Concurso Público", "Educação"});
        dados.add(new Object[]{593, null, null, null});
        dados.add(new Object[]{594, "Federal", "Concurso Público", "Administração e Educação"});
        dados.add(new Object[]{595, "Estadual", "Concurso Público", "Agropecuário"});
        dados.add(new Object[]{596, "Estadual", "Concurso Público", "Administração"});
        dados.add(new Object[]{597, "Municipal", "Concurso Público", "Jurídico e Administração"});
        dados.add(new Object[]{598, "Municipal", "Concurso Público", "Educação"});
        dados.add(new Object[]{599, "Municipal", "Concurso Público", "Jurídico e Administração"});
        dados.add(new Object[]{600, "Municipal", "Concurso Público", "Educação, Administração, Técnico, Engenheiro"});
        dados.add(new Object[]{601, "Federal", "Concurso Público", "Jurídico e Segurança"});
        dados.add(new Object[]{602, "Municipal", "Concurso Público", "Jurídico e Administração"});
        dados.add(new Object[]{603, "Municipal", "Concurso Público", "Saúde, Administração, Motorista, Analista e Procurador"});
        dados.add(new Object[]{604, "Estadual", "Concurso Público", "Segurança"});
        dados.add(new Object[]{605, "Estadual", "Processo Seletivo", "Saúde"});
        dados.add(new Object[]{606, null, null, null});
        dados.add(new Object[]{607, "Estadual", "Concurso Público", "Administração"});
        dados.add(new Object[]{608, "Estadual", "Concurso Público", "Meio Ambiente"});
        dados.add(new Object[]{609, "Federal", "Processo Seletivo", "Administração"});
        dados.add(new Object[]{610, "Municipal", "Concurso Público", "Educação"});
        dados.add(new Object[]{611, "Estadual", "Concurso Público", "Segurança"});
        dados.add(new Object[]{612, "Federal", "Processo Seletivo", "TI"});
        dados.add(new Object[]{613, "Estadual", "Concurso Público", "Administração"});
        dados.add(new Object[]{614, null, null, null});
        dados.add(new Object[]{615, "Estadual", "Concurso Público", "Jurídico e Administração"});
        dados.add(new Object[]{616, "Municipal", "Processo Seletivo", "Administração"});
        dados.add(new Object[]{617, "Estadual", "Concurso Público", "Administração"});
        dados.add(new Object[]{618, "Estadual", "Concurso Público", "Administração"});
        dados.add(new Object[]{619, "Estadual", "Concurso Público", "Administração"});




        return dados;

    }
}
