version: '3.8'
services:
  apidw:
    image: ${CI_REGISTRY_IMAGE}:${BUILD_VERSION}
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    networks:
      - proxy-reverse
    deploy:
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.apidw.entrypoints=websecure,web"
        - "traefik.http.routers.apidw.rule=Host(`${DOMINIO_APP}`)"
        - "traefik.http.routers.apidw.service=apidw"
        - "traefik.http.routers.apidw.tls.certresolver=letsencrypt"
        - "traefik.http.services.apidw.loadbalancer.server.port=8080"

networks:
  proxy-reverse:
    external: true
