version: '3.8'
services:
  api_dw:
    image: ${CI_REGISTRY_IMAGE}:${BUILD_VERSION}
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - DB_HOST=$DB_HOST
      - DB_NAME=$DB_NAME
      - DB_USER=$DB_USER
      - DB_PASSWORD=$DB_PASSWORD
    networks:
      - proxy-reverse
    deploy:
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.api_dw.entrypoints=websecure,web"
        - "traefik.http.routers.api_dw.rule=Host(`${DOMINIO_APP}`)"
        - "traefik.http.routers.api_dw.service=api_dw"
        - "traefik.http.routers.api_dw.tls.certresolver=letsencrypt"
        - "traefik.http.services.api_dw.loadbalancer.server.port=8080"

networks:
  proxy-reverse:
    external: true
